steps:
  # 1. Restore dependencies
  # Use the official .NET 8 SDK image from Microsoft's container registry.
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    entrypoint: 'dotnet'
    args: ['restore', '${_PROJECT_NAME}/${_PROJECT_NAME}.csproj']
    id: 'restore'

  # 2. Compile source code
  # This step builds the project in Release configuration.
  # The --no-restore flag is used because dependencies were restored in the previous step.
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    entrypoint: 'dotnet'
    args:
      - 'build'
      - '${_PROJECT_NAME}/${_PROJECT_NAME}.csproj'
      - '--configuration'
      - 'Release'
      - '--no-restore'
    id: 'build'
    waitFor: ['restore']

  # 3. Execute unit tests
  # This step runs tests. I've assumed your test project is in a directory
  # named 'PSCourseLibrary.Tests'. You should adjust the path if it's different.
  # The --no-build flag is used because the project was already built.
  - name: 'mcr.microsoft.com/dotnet/sdk:8.0'
    entrypoint: 'dotnet'
    args:
      - 'test'
      - '${_PROJECT_NAME}.Tests/${_PROJECT_NAME}.Tests.csproj' # Uncomment and update if you have a test project
      - '--configuration'
      - 'Release'
#      - '--no-build'
    id: 'test'
    waitFor: ['build']

  # 4. Build the Docker image
  # This step builds the Docker image using the Dockerfile in the project directory.
  # The image is tagged with the Google Container Registry (GCR) path, project ID, and short commit SHA.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'
      - '${_PROJECT_NAME}' # Assumes your Dockerfile is in the ${_PROJECT_NAME} directory
    id: 'docker-build'
    waitFor: ['test']

  # 5. Push the Docker image to Google Container Registry
  # This step pushes the tagged image to GCR.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA']
    id: 'docker-push'
    waitFor: ['docker-build']

substitutions:
  _PROJECT_NAME: CityInfo.API
  _IMAGE_NAME: cityinfo-api
  _PROJECT_ID: vaulted-scholar-476714-g4
  _SHORT_SHA: 1.0.0

options:
  logging: CLOUD_LOGGING_ONLY
